# Generated by Django 2.0.4 on 2018-05-02 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fileset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expt_type', models.CharField(choices=[('node', 'node'), ('cloud', 'cloud'), ('emu', 'emu')], max_length=8)),
                ('time_created', models.DateTimeField()),
                ('log', models.URLField()),
                ('report', models.URLField()),
                ('graph1', models.URLField()),
                ('graph2', models.URLField()),
                ('flows', models.IntegerField()),
                ('runs', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme', models.CharField(max_length=32)),
                ('run', models.IntegerField()),
                ('flow', models.IntegerField()),
                ('throughput', models.FloatField()),
                ('delay', models.FloatField()),
                ('loss', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CloudExpt',
            fields=[
                ('fileset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pantheon.Fileset')),
                ('src', models.CharField(max_length=64)),
                ('dst', models.CharField(max_length=64)),
            ],
            bases=('pantheon.fileset',),
        ),
        migrations.CreateModel(
            name='EmuExpt',
            fields=[
                ('fileset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pantheon.Fileset')),
                ('scenario', models.IntegerField()),
                ('emu_cmd', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=255)),
            ],
            bases=('pantheon.fileset',),
        ),
        migrations.CreateModel(
            name='NodeExpt',
            fields=[
                ('fileset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pantheon.Fileset')),
                ('node', models.CharField(max_length=64)),
                ('cloud', models.CharField(max_length=64)),
                ('to_node', models.BooleanField()),
                ('link', models.CharField(max_length=64)),
            ],
            bases=('pantheon.fileset',),
        ),
        migrations.AddField(
            model_name='ranking',
            name='expt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pantheon.Fileset'),
        ),
    ]
