# Generated by Django 2.0.5 on 2018-05-04 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantheon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emuexpt',
            name='emu_cmd',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='emuexpt',
            name='emu_scenario',
            field=models.IntegerField(choices=[(1, 'Calibrated emulator (Nepal to AWS India)'), (2, 'Calibrated emulator (Mexico cellular to AWS California)'), (3, 'Calibrated emulator (AWS Brazil to Colombia cellular)'), (4, 'Calibrated emulator (India to AWS India)'), (5, 'Calibrated emulator (AWS Korea to China)'), (6, 'Calibrated emulator (AWS California to Mexico)'), (7, 'Token-bucket based policer (bandwidth 12mbps, RTT 20ms)'), (8, 'Token-bucket based policer (bandwidth 60mbps, RTT 20ms)'), (9, 'Token-bucket based policer (bandwidth 108mbps, RTT 20ms)'), (10, 'Token-bucket based policer (bandwidth 12mbps, RTT 100ms)'), (11, 'Token-bucket based policer (bandwidth 60mbps, RTT 100ms)'), (12, 'Token-bucket based policer (bandwidth 108mbps, RTT 100ms)'), (13, 'Severe ACK aggregation (1 ACK every 100ms)'), (14, 'Severe ACK aggregation (10 ACKs every 200ms)'), (15, 'Bottleneck buffer = BDP/10'), (16, 'Bottleneck buffer = BDP/3'), (17, 'Bottleneck buffer = BDP/2'), (18, 'Bottleneck buffer = BDP')]),
        ),
        migrations.AlterField(
            model_name='fileset',
            name='scenario',
            field=models.CharField(choices=[('1_flow', '1 flow'), ('3_flows', '3 flows')], max_length=16),
        ),
    ]
