# Generated by Django 2.0.4 on 2018-05-23 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantheon', '0003_remove_perf_flow'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileset',
            name='perf_file',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
    ]
